# Generated by Django 5.2.12 on 2026-03-09 06:14

import django.db.models.deletion
import utils.file_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=12)),
                ('contact_person', models.CharField(max_length=120)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='hospital_docs/', validators=[utils.file_validators.validate_hospital_doc])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospitals_hospital',
            },
        ),
    ]
