# Generated by Django 5.2.12 on 2026-03-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_stocks', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'blood_stock_blood_stock',
                'indexes': [models.Index(fields=['blood_group', 'expiry_date'], name='blood_stock_blood_g_15d8c1_idx'), models.Index(fields=['hospital', 'blood_group'], name='blood_stock_hospita_e22402_idx')],
            },
        ),
    ]
