# Generated by Django 5.2.12 on 2026-03-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bloodstock',
            name='blood_stock_hospita_e22402_idx',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='hospital',
        ),
    ]
