# Generated by Django 5.2.12 on 2026-03-11 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification_email_alter_otpverification_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be in valid international format.', regex='^\\+?[1-9]\\d{9,14}$')]),
        ),
    ]
